server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Hỗ trợ React Router (Bất kỳ URL nào cũng trả về index.html thay vì báo lỗi 404)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bật nén file tĩnh để tăng tốc load web
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1000;
}
